### ISSUE TITLE
Migrate image from alpine to ubuntu light

### ISSUE THREAD

**Issue by piosz** [kubernetes/heapster#1284]

**Comment by bprashanth** [comment]
if this is for the dns issue I believe it's fixed in later versions of alpine (>=3.4 from memory)

**Comment by piosz** [comment]
Thanks @bprashanth for the info. Anyway since we have our own trusted image it'd be better to use it.

**Comment by clhodapp** [comment]
See https://github.com/rancher/rancher/issues/4451#issuecomment-245676039

**Comment by clhodapp** [comment]
The test I performed at the end of https://github.com/rancher/rancher/issues/4451#issuecomment-245698975 presents pretty direct evidence that there is still an issue with DNS in Alpine.

**Comment by piosz** [comment]
Thanks for the info. I'm prioritizing this issue.

**Comment by DirectXMan12** [comment]
@piosz what's the status of this
